network:
  version: 2
  # if specified globally, can only realistically have that value,
  # as networkd cannot render wifi/3G.
  renderer: NetworkManager
  bridges:
    # greenzone
    br0:
      dhcp4: false
      addresses: [192.168.3.1/24]
      gateway4: 192.168.3.1
      nameservers:
        addresses: [192.168.3.1]

    # redzone
    br1:
      dhcp4: false
      addresses: [192.168.4.1/24]
      gateway4: 192.168.4.1
      nameservers:
        addresses: [192.168.4.1]

